kumuluzee:
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  name: employees-service
  version: 1.0.0
  env:
    name: dev

  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://159.122.187.27:32132

  discovery:
    etcd:
      hosts: http://159.122.187.27:32132
    ttl: 20
    ping-interval: 15

  metrics:
    web-instrumentation:
    - name: employees-endpoint
      url-pattern: /v1/employees/*
    - name: demo-endpoint
      url-pattern: /v1/demo/*

app-properties:
  external-services:
    enabled: true
  healthy: true