apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: kr3037/simpleshift-employees:latest
        name: employees
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: employees
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employees