apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: kr3037/simpleshift-employees:0.11
        name: employees
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: bluemix
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://159.122.187.27:30385
        - name: KUMULUZEE_ENV_NAME
          value: kub
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3